
# Get All Books
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json


###
# Create a Book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "The Great Gatsby"
}

###
# Update a Book
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title":"Harry Potter"
}


###
# Delete a Book
DELETE http://localhost:3001/books/3 HTTP/1.1
Content-Type: application/json